name: CI

on:
  push:
    branches:
      - '*'  # Trigger on any branch
  pull_request:
    branches:
      - '*'  # Trigger on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.17.1'

    - name: Install dependencies
      run: sudo apt-get install -y g++ libgtest-dev

    - name: Build GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Configure CMake
      run: cmake -S . -B build -Dgtest_ct_build_tests=ON

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build
