name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmake-version: '3.17.1'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        
    - name: Build and Install GoogleTest
      run: |
        git clone https://github.com/google/googletest.git -b release-1.12.1
        cd googletest
        cmake -Bbuild -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        cmake --build build --config Release
        sudo cmake --build build --target install
        cd ..
        
    - name: Configure CMake
      working-directory: ${{ github.workspace }}
      run: cmake -S . -B build -Dgtest_ct_build_tests=ON
      
    - name: Build
      run: cmake --build build
      
    - name: Run Tests
      run: ctest --test-dir build --output-on-failure