name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3
        with:
          cmakeVersion: '3.13.0'  # Ensure this is >= 3.13 for compatibility with your project

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ # Install CMake and g++ for building the project

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake -S . -B build -Dgtest_ct_build_tests=ON

      - name: Build with CMake
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
