name: CTest Complex Matrix Build

on:
  push:
    branches:
      - '*'      
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cpp_standard: [11, 14, 17, 20, 23]

        include:
          # C++11 builds will use Google Test 1.12.1
          - cpp_standard: 11
            gtest_ref: release-1.12.1

          # C++14, 17, 20, 23 builds will use Google Test 1.14.0
          - cpp_standard: 14
            gtest_ref: release-1.14.0
          - cpp_standard: 17
            gtest_ref: release-1.14.0
          - cpp_standard: 20
            gtest_ref: release-1.14.0
          - cpp_standard: 23
            gtest_ref: release-1.14.0

    steps:
      - uses: actions/checkout@v4

      - name: Clone Google Test ${{ matrix.gtest_ref }}
        run: |
          git clone https://github.com/google/googletest.git -b ${{ matrix.gtest_ref }} googletest

      - name: Build Google Test (for C++ ${{ matrix.cpp_standard }})
        run: |
          GT_BUILD_CXX_STANDARD="${{ matrix.cpp_standard }}"
          if [ "${{ matrix.gtest_ref }}" = "release-1.12.1" ]; then
            GT_BUILD_CXX_STANDARD="17"
          fi

          cmake -S googletest -B googletest/build -DCMAKE_CXX_STANDARD=$GT_BUILD_CXX_STANDARD
          cmake --build googletest/build

      - name: Configure and Build Project (with C++ ${{ matrix.cpp_standard }})
        run: |
          cmake -S . -B build \
                -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }} \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin
          cmake --build build

      - name: Run Tests (for C++ ${{ matrix.cpp_standard }})
        run: ./bin/passing_tests
